const Faq = () => {
  return (
    <div className="bg-slate-100 p-4 px-5 rounded-2xl text-slate-500">
      <h2 className="text-black my-2">How do I get my staking rewards?</h2>
      <p>
        Staking rewards are accrued differently between the Native and mSOL
        products. With Native, more SOL is sent to your stake account after each
        epoch (2-3 days). If you liquid stake using mSOL, mSOL is a
        rewards-bearing liquid staking token that grows over time vs. SOL price.
        That means your staking rewards generated by the Marinade stake pool are
        automatically added to the price of mSOL after each epoch. When you
        unstake your mSOL, you will receive a greater amount of SOL tokens based
        on how long you have held the mSOL. See mSOL/SOL price
      </p>
      <h2 className="text-black my-2">
        How do I receive my SOL back if I choose “Delayed Unstake”?
      </h2>
      <p>
        You can unstake your mSOL at the end of each Solana epoch (every 2-3
        days) with no fee, but this requires you to return to the DApp to claim
        it once available. To unstake and receive your SOL, visit the Marinade
        DApp’s “Delayed unstake” option and “Start delayed unstake.” After the
        announced time, return to the DApp and click on the “unstake” tab and
        you will see any delayed unstake tickets that is ready to be claimed
        will be displayed and you can make one more transaction to claim your
        SOL. When you start delayed unstake, you will be prompted to sign up for
        Dialect notifications that will alert you when your SOL stake is ready
        to be claimed. There is no expiration date to return and claim your
        unstaked SOL.
      </p>
      <h2 className="text-black my-2">
        Can I unstake mSOL or my Native SOL stake at any time?
      </h2>
      <p>
        Yes. Marinade allows you to directly swap your mSOL back to SOL by using
        our ‘Unstake now’ option. You can instantly unstake your mSOL anytime
        for SOL. This option returns SOL instantly but comes with a liquidity
        fee of 0.01% or higher depending on the route that Marinade will find
        for you. Marinade’s liquidity router utilizes multiple sources and is
        always identifying the best unstake route so you get the most SOL out of
        your instant unstake. You can learn more about our fee structure. You
        can also unstake without any fee by using our ‘Delayed unstake’ option.
      </p>
      <h2 className="text-black my-2">
        Why can I not see my staked SOL after I deposited the mSOL on another
        protocol?
      </h2>
      <p>
        Marinade's dashboard only shows funds that are in your wallet and not
        used in DeFi. In order to see your positions across the ecosystem, use
        apps like step.finance or sonar.watch. Your mSOL is accruing staking
        rewards even if it is not displayed in our dashboard.
      </p>
    </div>
  );
};

export default Faq;
